prod.yaml fixed

diff --git a/.github/workflows/prod.yaml b/.github/workflows/prod.yaml
--- a/.github/workflows/prod.yaml
+++ b/.github/workflows/prod.yaml
@@ -5,10 +5,16 @@ on:
       - 'main'
 jobs:
   BuildSimulation:
-    # TODO abort this workflow if the git user triggered it is not the release manager
+    # TODO ***done*** abort this workflow if the git user triggered it is not the release manager
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
+      - name: Check Release Manager
+        run: |
+          if [ "${{ github.actor }}" != "davidhei" ]; then
+            echo "This workflow can only be triggered by the release manager. Aborting..."
+            exit 1
+          fi
       - name: Build
         run: |
           echo building and packing and app...
